test-docker-*-arm: try ubuntu arm32v7

diff --git a/.github/workflows/test-docker-linux-arm.yml b/.github/workflows/test-docker-linux-arm.yml
--- a/.github/workflows/test-docker-linux-arm.yml
+++ b/.github/workflows/test-docker-linux-arm.yml
@@ -236,22 +236,52 @@ jobs:
   ubuntu-arm:
     name: 'arm Ninja Build ${{ github.event.inputs.version }} test on Ubuntu 18 stable'
     runs-on: [self-hosted, linux, arm64, xbbla]
+    container:
+      image: arm32v7/ubuntu:18.04
+      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontaineroptions
+      options: --platform linux/arm/v7
+    defaults:
+      run:
+        # -l (--login) for the node PATH
+        shell: /usr/bin/linux32 /bin/bash -e -o pipefail -l {0}
+
     steps:
       - name: 'Machine'
         run: uname -a
+
+      - name: 'Update'
+        run: |
+          apt-get -qq update
+          # binutils for readelf
+          apt-get -qq install -y lsb-release git-core curl tar gzip binutils
+          apt-get -qq install nodejs
+
+      - name: 'Clean working area'
+        run: rm -rf * .git*
+
       - name: 'Checkout'
-        uses: actions/checkout@v2
+        uses: actions/checkout@v1
         with:
           fetch-depth: 3
+
+      - name: 'Install xpm'
+        timeout-minutes: 1440
+        run: npm install --location=global xpm@latest
+
+      - name: 'Install project dependencies'
+        timeout-minutes: 1440
+        run: xpm install
+
+
       # docker://arm32v7/ubuntu:20.04 - fails to update
-      - name: 'Ubuntu 18.04 arm'
-        uses: docker://arm32v7/ubuntu:18.04
-        with:
-          entrypoint: /usr/bin/linux32
-          args: /bin/bash /github/workspace/scripts/helper/tests/native-test.sh --image arm32v7/ubuntu:18.04 --version ${{ github.event.inputs.version }} --base-url ${{ github.event.inputs.base_url }}
+      - name: 'Run ${{ github.event.inputs.version }} docker test'
+        run: xpm run test-native -- --version ${{ github.event.inputs.version }} --base-url ${{ github.event.inputs.base_url }} --image debian
+
+  # docker://arm32v7/ubuntu:20.04 - fails to update
 
   # https://hub.docker.com/r/arm32v7/debian
   debian-arm:
+    if: ${{ false }}
     name: 'arm Ninja Build ${{ github.event.inputs.version }} test on Debian 10 stable'
     runs-on: [self-hosted, linux, arm64, xbbla]
     steps:
